require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/**/*
