require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*

Metrics/AbcSize:
  Exclude:
    - app/controllers/*

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/**/*
