name: Rspec

on:
  push:
    branches:
      - '**'

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: localhost

jobs:
  Rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Workflow access
        uses: actions/checkout@v3

      - name: Build app
        uses: ./.github/actions/prebuild_app

      - name: Setup DB
        run: bin/rails db:setup

      - name: Run rspec tests
        run: |
          bin/rails assets:precompile
          bundle exec rspec spec
